# Generated by Django 4.1.4 on 2023-01-01 06:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calmenuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMenuCalender',
            new_name='UserCalMenu',
        ),
    ]
