# Generated by Django 4.1.4 on 2023-01-08 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calmenuapp', '0002_rename_usermenucalender_usercalmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usercart',
            old_name='date',
            new_name='day',
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='types',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='edate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='sdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='UserCalMenu',
        ),
        migrations.AddField(
            model_name='event',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calmenuapp.menu'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
