# Generated by Django 4.1.4 on 2023-01-08 07:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calmenuapp', '0003_event_rename_date_usercart_day_alter_menu_meal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='CalMenu',
        ),
    ]
