# Generated by Django 4.1.4 on 2023-01-08 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calmenuapp', '0004_rename_event_calmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCalMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=200)),
                ('types', models.CharField(blank=True, max_length=100)),
                ('meal', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserCart',
            new_name='MyCart',
        ),
        migrations.RenameField(
            model_name='grocery',
            old_name='ingredient',
            new_name='item',
        ),
        migrations.DeleteModel(
            name='CalMenu',
        ),
        migrations.AddField(
            model_name='mycalmenu',
            name='menuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calmenuapp.mymenu'),
        ),
    ]
