# Generated by Django 4.1.4 on 2023-01-08 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calmenuapp', '0005_mycalmenu_myitem_mymenu_rename_usercart_mycart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calmenuapp.myitem')),
                ('menuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calmenuapp.mymenu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
