# Generated by Django 4.1.4 on 2023-01-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calmenuapp', '0006_mymenuitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='types',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='mymenu',
            old_name='types',
            new_name='category',
        ),
    ]
