# Generated by Django 4.1.4 on 2023-01-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calmenuapp', '0007_rename_types_menu_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalmenu',
            name='day',
            field=models.DateField(),
        ),
    ]
