# Generated by Django 4.1.4 on 2023-01-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calmenuapp', '0008_alter_mycalmenu_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='category',
        ),
    ]
