# Generated by Django 4.1.4 on 2023-01-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calmenuapp', '0009_remove_grocery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='category',
            field=models.CharField(blank=True, choices=[('고기', '고기'), ('야채', '야채'), ('생선', '생선'), ('과일', '과일'), ('곡류', '곡류'), ('유제품', '유제품'), ('냉동식품', '냉동식품'), ('냉장식품', '냉장식품'), ('음료', '음료'), ('소스', '소스'), ('기타', '기타')], max_length=100),
        ),
    ]
