# Generated by Django 4.1.4 on 2023-01-10 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calmenuapp', '0010_grocery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycalmenu',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myitem',
            name='category',
            field=models.CharField(blank=True, choices=[('고기', '고기'), ('야채', '야채'), ('생선', '생선'), ('과일', '과일'), ('곡류', '곡류'), ('유제품', '유제품'), ('냉동식품', '냉동식품'), ('냉장식품', '냉장식품'), ('음료', '음료'), ('소스', '소스'), ('기타', '기타')], max_length=100),
        ),
    ]
