# Generated by Django 4.1.4 on 2023-01-10 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calmenuapp', '0011_mycalmenu_user_alter_myitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycalmenu',
            old_name='user',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='myitem',
            old_name='user',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='mymenu',
            old_name='user',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='mymenuitems',
            old_name='user',
            new_name='userid',
        ),
    ]
