# Generated by Django 4.1.4 on 2023-01-11 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calmenuapp', '0012_rename_user_mycalmenu_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal',
            field=models.CharField(blank=True, choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁'), ('간식', '간식'), ('도시락', '도시락'), ('기타', '기타')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mymenu',
            name='category',
            field=models.CharField(blank=True, choices=[('수프', '수프'), ('빵', '빵'), ('면', '면'), ('밥', '밥'), ('국', '국'), ('죽', '죽'), ('반찬', '반찬'), ('도시락', '도시락'), ('고기', '고기'), ('생선', '생선'), ('분식', '분식'), ('전골', '전골'), ('손님초대', '손님초대'), ('외식', '외식'), ('기타', '기타')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mymenu',
            name='meal',
            field=models.CharField(blank=True, choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁'), ('간식', '간식'), ('도시락', '도시락'), ('기타', '기타')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mymenu',
            name='userid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
