# Generated by Django 4.1.4 on 2023-01-11 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calmenuapp', '0013_alter_menu_meal_alter_mymenu_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymenu',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
