# Generated by Django 4.1.4 on 2023-01-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calmenuapp', '0015_alter_myitem_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymenu',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myitem',
            name='category',
            field=models.CharField(blank=True, choices=[('빵', '빵'), ('고기', '고기'), ('야채', '야채'), ('생선', '생선'), ('과일', '과일'), ('곡류', '곡류'), ('유제품', '유제품'), ('냉동식품', '냉동식품'), ('냉장식품', '냉장식품'), ('음료', '음료'), ('소스', '소스'), ('기타', '기타')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mymenu',
            name='category',
            field=models.CharField(blank=True, choices=[('수프', '수프'), ('빵', '빵'), ('면', '면'), ('밥', '밥'), ('국', '국'), ('죽', '죽'), ('반찬', '반찬'), ('도시락', '도시락'), ('고기', '고기'), ('생선', '생선'), ('분식', '분식'), ('전골', '전골'), ('손님초대', '손님초대'), ('외식', '외식'), ('*기타', '기타')], max_length=100),
        ),
    ]
